name: "Moodle Plugin Version Generator"
author: "Gerardo Grinman <gerardo.grinman@aprende.com>"
description: "Increase the moodle plugin version"
inputs:
  path:
    description: "Path where the repository is located"
    required: false
    default: '.'
  files_changed:
    required: true
    description: Boolean indicating that files have changed.
    default: 'false'
  changed_files:
    required: true
    description: List of changed files
outputs:
  version:
    description: "A version.php file updated to the Pull-Request."
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.changed_files }}
branding:
  icon: 'book'
  color: 'blue'

