name: "Moodle Plugin Version Generator"
author: "Gerardo Grinman <gerardo.grinman@aprende.com>"
description: "Increase the moodle plugin version"
inputs:
  path:
    description: "Path where the repository is located"
    required: false
    default: '.'
  verify-changed-files:  
    description: 'verify changed files'
    required: true
    default: 'false'
outputs:
  version:
    description: "A version.php file updated to the Pull-Request."
  changed files:
    description: "changed files"
    value: ${{ steps.verify-changed-files.outputs.changed_files }}
runs:
  if: steps.verify-changed-files.outputs.files_changed == 'true'
  using: 'docker'
  image: 'Dockerfile'
  steps:
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v12
      id: verify-changed-files
      with:
        files: |
           db
    - name: Run step only when any of the above files change.
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
      # Outputs: "Changed files: db "
    - name: Perform action when test_directory changes
      if: contains(steps.verify-changed-files.outputs.changed_files, 'db')
      run: |
        echo "db directory has changed."
branding:
  icon: 'book'
  color: 'blue'
